#!/usr/bin/env python3
"""
app2nix - Convert .deb packages to NixOS expressions.

Usage:
    python main.py <deb-file>           # Analyze and generate default.nix
    python main.py --url <url>          # Download and analyze .deb from URL
    python main.py --json <file>        # Generate from JSON descriptor
"""

import argparse
import json
import os
import sys
import urllib.request

from analyze_deb import get_all_dependencies
from lib.deb_to_nix import translate_all

DEFAULT_NIX_TEMPLATE = """{{ pkgs ? import <nixpkgs> {{}} }}:
let
  # Auto-generated by app2nix
  autoPatchelfHook = pkgs.makeSetupHook {{
    name = "auto-patchelf";
    passthru = {{
      libPath = lib.makeLibraryPath deps;
      nativeLibDepends = [];
    }};
  }};
in
pkgs.stdenv.mkDerivation {{
  name = "{name}";
  version = "{version}";
  src = ./.;

  nativeBuildInputs = [
    pkgs.autoPatchelfHook
{deps}
  ];

  installPhase = ''
    mkdir -p $out/bin
    mkdir -p $out/lib
    cp -r usr/share/* $out/share/ 2>/dev/null || true
    cp -r opt/* $out/opt/ 2>/dev/null || true
    cp -r etc/* $out/etc/ 2>/dev/null || true
$install_extras
  '';

  fixupOutput = "hook";
}}
"""


def download_deb(url: str, dest: str = "/tmp/app2nix_download.deb"):
    """Download .deb from URL."""
    print(f"Downloading {url}...")
    urllib.request.urlretrieve(url, dest)
    return dest


def analyze_deb_file(deb_path: str) -> dict:
    """Analyze .deb and return dependency info."""
    if not os.path.exists(deb_path):
        print(f"Error: File not found: {deb_path}", file=sys.stderr)
        sys.exit(1)

    info = get_all_dependencies(deb_path)
    return info


def generate_default_nix(info: dict, output_dir: str = ".") -> str:
    """Generate default.nix from dependency info."""
    name = info.get("name", "app")
    version = info.get("version", "1.0")
    deps = info.get("dependencies", [])

    nix_deps = translate_all(deps)

    deps_lines = ""
    for dep in nix_deps:
        if dep.startswith("#"):
            deps_lines += f"    # pkgs.{dep[1:]} # Not found in nixpkgs\n"
        else:
            deps_lines += f"    pkgs.{dep}\n"

    install_extras = ""
    if info.get("executables"):
        install_extras += "\n    # Fix shebang and create bin entries\n"

    content = DEFAULT_NIX_TEMPLATE.format(
        name=name,
        version=version,
        deps=deps_lines.rstrip(),
        install_extras=install_extras
    )

    output_path = os.path.join(output_dir, "default.nix")
    with open(output_path, "w") as f:
        f.write(content)

    return output_path


def create_json_from_deb(deb_path: str, output_path: str | None = None) -> str:
    """Create JSON descriptor from .deb."""
    info = analyze_deb_file(deb_path)

    nix_deps = translate_all(info.get("dependencies", []))

    output = {
        "name": info.get("name", "unknown"),
        "version": info.get("version", "1.0"),
        "architecture": info.get("architecture", "amd64"),
        "dependencies": nix_deps,
        "libraries": info.get("dependencies", [])
    }

    json_str = json.dumps(output, indent=2)

    if output_path:
        with open(output_path, "w") as f:
            f.write(json_str)
        return output_path
    else:
        return json_str


def main():
    parser = argparse.ArgumentParser(
        description="Convert .deb packages to NixOS expressions"
    )
    parser.add_argument(
        "deb_file",
        nargs="?",
        help="Path to .deb file"
    )
    parser.add_argument(
        "--url",
        help="URL to download .deb from"
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Output JSON descriptor instead of default.nix"
    )
    parser.add_argument(
        "--output", "-o",
        help="Output file (default.nix or descriptor.json)"
    )
    parser.add_argument(
        "--output-dir", "-d",
        default=".",
        help="Output directory"
    )
    parser.add_argument(
        "--print-deps",
        action="store_true",
        help="Only print dependencies"
    )
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Verbose output"
    )

    args = parser.parse_args()

    deb_path = args.deb_file

    if args.url:
        deb_path = download_deb(args.url)

    if not deb_path:
        parser.print_help()
        sys.exit(1)

    info = analyze_deb_file(deb_path)

    if args.print_deps:
        deps = info.get("dependencies", [])
        nix_deps = translate_all(deps)
        print("Debian libraries:", *deps, sep="\n")
        print("\nNixpkgs packages:", *nix_deps, sep="\n")
        sys.exit(0)

    if args.json:
        create_json_from_deb(deb_path, args.output)
        output = args.output or "descriptor.json"
        print(f"Generated: {output}")
    else:
        generate_default_nix(info, args.output_dir)
        print(f"Generated: {args.output_dir}/default.nix")

    if args.verbose:
        print("\nPackage info:")
        print(f"  Name: {info.get('name')}")
        print(f"  Version: {info.get('version')}")
        print(f"  Architecture: {info.get('architecture')}")
        print(f"  Libraries: {len(info.get('dependencies', []))}")
        print(f"  Executables: {len(info.get('executables', []))}")


if __name__ == "__main__":
    main()
