services:
  - type: web
    name: app2nix
    env: docker
    dockerfilePath: Dockerfile
    dockerCommand: python server.py
    plan: free
    region: frankfurt
    healthCheckPath: /api
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
