import difflib

from app2nix.models import ResolvedDependency

DEP_MAP = {
    "webkit2gtk-4.1": "webkitgtk_4_1",
    "webkit2gtk-4.0": "webkitgtk_4_1",
    "webkit2gtk-6.0": "webkitgtk_6_0",
    "javascriptcoregtk-4.1": "webkitgtk_4_1",
    "javascriptcoregtk-4.0": "webkitgtk_4_1",
    "javascriptcoregtk-6.0": "webkitgtk_6_0",
    "soup-3.0": "libsoup_3",
    "soup-2.4": "libsoup_2_4",
    "secret-1": "libsecret",
    "drm": "libdrm",
    "gbm": "mesa",
    "vulkan": "vulkan-loader",
    "gtk-3": "gtk3",
    "gdk-3": "gtk3",
    "pango-1": "pango",
    "cairo": "cairo",
    "freetype": "freetype",
    "fontconfig": "fontconfig",
    "expat": "expat",
    "dbus-1": "dbus",
    "glib": "glib",
    "gobject-2": "glib",
    "nss": "nss",
    "nspr": "nspr",
    "z": "zlib",
    "zstd": "zstd",
    "bz2": "bzip2",
    "lzma": "xz",
    "xz": "xz",
    "gcrypt": "libgcrypt",
    "gpg-error": "libgpg-error",
    "gnutls": "gnutls",
    "nettle": "nettle",
    "ssl": "openssl",
    "crypto": "openssl",
    "OpenGL": "mesa",
    "GL": "libGL",
    "GLU": "libGLU",
    "glut": "freeglut",
    "glew": "glew",
    "glfw": "glfw",
    "xcb": "xorg.libxcb",
    "xkbcommon": "xkbcommon",
    "X11": "libX11",
    "Xext": "libXext",
    "Xrandr": "libXrandr",
    "Xi": "libXi",
    "Xinerama": "libXinerama",
    "Xcursor": "libXcursor",
    "Xdamage": "libXdamage",
    "wayland-client": "wayland",
    "asound": "alsa-lib",
    "pulse": "libpulse",
    "jack": "jack2",
    "opus": "opus",
    "vorbis": "libvorbis",
    "sndfile": "libsndfile",
    "avcodec": "ffmpeg",
    "avformat": "ffmpeg",
    "avutil": "ffmpeg",
    "swscale": "ffmpeg",
    "Qt5Core": "qt5.qtbase",
    "Qt5Widgets": "qt5.qtbase",
    "Qt5Gui": "qt5.qtbase",
    "Qt5Xml": "qt5.qtxmlpatterns",
    "Qt5Sql": "qt5.qtbase",
    "Qt5Network": "qt5.qtbase",
    "Qt5OpenGL": "qt5.qtbase",
    "Qt5Quick": "qt5.qtdeclarative",
    "Qt5Qml": "qt5.qtdeclarative",
    "Qt5WebEngine": "qt5.qtwebengine",
    "Qt6Core": "qt6.qtbase",
    "Qt6Widgets": "qt6.qtbase",
    "Qt6Gui": "qt6.qtbase",
    "Qt6Sql": "qt6.qtbase",
    "Qt6Network": "qt6.qtbase",
    "Qt6OpenGL": "qt6.qtbase",
    "Qt6Quick": "qt6.qtdeclarative",
    "Qt6Qml": "qt6.qtdeclarative",
    "Qt6WebEngine": "qt6.qtwebengine",
    "Qt6Svg": "qt6.qtsvg",
    "png": "libpng",
    "jpeg": "libjpeg",
    "tiff": "tiff",
    "webp": "libwebp",
    "sqlite3": "sqlite",
    "pq": "postgresql",
    "curl": "curl",
    "ssh": "libssh",
    "nghttp2": "nghttp2",
    "ldap": "openldap",
    "python3.11": "python311",
    "python3.12": "python312",
    "python3": "python3",
    "python3Full": "python3",
    "boost_system": "boost",
    "boost_filesystem": "boost",
    "boost_regex": "boost",
    "boost_python3": "boost",
    "uuid": "util-linux",
    "blkid": "util-linux",
    "selinux": "libselinux",
    "sepol": "libsepol",
    "audit": "audit",
    "cap": "libcap",
    "acl": "acl",
    "attr": "attr",
    "pcre": "pcre",
    "pcre2": "pcre2",
    "json-glib-1": "json-glib",
    "archive": "libarchive",
    "usb-1": "libusb",
    "udev": "systemd",
    "systemd": "systemd",
    "cups": "cups",
    "gtk2": "gtk2",
    "gdk-x11-3": "gtk3",
    "gtk-x11-2": "gtk2",
    "gtkgl": "gtkglext",
    "champlain": "libchamplain",
    "clutter": "clutter",
    "gdl": "gdl",
    "keybinder": "keybinder",
    "appindicator": "libappindicator",
    "notify": "libnotify",
    "gstreamer-1": "gstreamer",
    "gstbase-1": "gst-plugins-base",
    "gstvideo-1": "gst-plugins-base",
    "gstaudio-1": "gst-plugins-base",
    "gsttag-1": "gst-plugins-base",
    "harfbuzz": "harfbuzz",
    "icuuc": "icu",
    "icui18n": "icu",
    "icudata": "icu",
    "SDL2": "SDL2",
    "tinfo": "ncurses",
    "ffi": "libffi",
    "pcre2-8": "pcre2",
    "xml2": "libxml2",
    "xslt": "libxslt",
    "graphite2": "graphite2",
    "evdev": "libevdev",
    "input": "libinput",
    "pam": "linux-pam",
    "apparmor": "apparmor",
    "seccomp": "libseccomp",
    "yara": "yara",
    "yaml": "yaml",
    "toml": "toml",
    "poppler": "poppler",
    "pixman": "pixman",
    "c": "glibc",
    "m": "glibc",
    "pthread": "glibc",
    "rt": "glibc",
    "resolv": "glibc",
    "dl": "glibc",
    "gcc_s": "gcc.cc.lib",
    "stdc++": "gcc.cc.lib",
    "atomic": "libatomic",
    "gdk_pixbuf-2.0": "gdk-pixbuf",
    "gio-2.0": "glib",
    "glib-2.0": "glib",
    "gmodule-2.0": "glib",
    "gobject-2.0": "glib",
    "atk-1.0": "atk",
    "atk-bridge-2.0": "at-spi2-atk",
    "atspi": "at-spi2-core",
    "X11-xcb": "xorg.libX11",
    "Xcomposite": "libXcomposite",
    "Xfixes": "libXfixes",
    "Xrender": "libXrender",
    "xcb-render": "xorg.libxcb",
    "xcb-shm": "xorg.libxcb",
    "avahi-client": "avahi",
    "avahi-common": "avahi",
    "brotlicommon": "brotli",
    "brotlidec": "brotli",
    "bsd": "libbsd",
    "cairo-gobject": "cairo",
    "colord": "colord",
    "com_err": "e2fsprogs",
    "enchant-2": "enchant2",
    "epoxy": "libepoxy",
    "fribidi": "fribidi",
    "gmp": "gmp",
    "gssapi_krb5": "krb5",
    "gstallocators-1.0": "gst-plugins-base",
    "gstapp-1.0": "gst-plugins-base",
    "gstfft-1.0": "gst-plugins-base",
    "gstgl-1.0": "gst-plugins-base",
    "gstpbutils-1.0": "gst-plugins-base",
    "gudev-1.0": "libgudev",
    "hogweed": "nettle",
    "hyphen": "hyphen",
    "idn2": "libidn2",
    "jbig": "jbigkit",
    "keyutils": "keyutils",
    "krb5": "krb5",
    "krb5support": "krb5",
    "lcms2": "lcms2",
    "lz4": "lz4",
    "mount": "util-linux",
    "openjp2": "openjpeg",
    "orc-0.4": "orc",
    "p11-kit": "p11-kit",
    "pangocairo-1.0": "pango",
    "pangoft2-1.0": "pango",
    "png16": "libpng",
    "psl": "libpsl",
    "rest-0.7": "rest",
    "rsvg-2": "librsvg",
    "soup-gnome-2.4": "libsoup_2_4",
    "tasn1": "libtasn1",
    "thai": "libthai",
    "unistring": "libunistring",
    "wayland-cursor": "wayland",
    "wayland-egl": "wayland",
    "wayland-server": "wayland",
    "webpdemux": "libwebp",
    "woff2common": "woff2",
    "woff2dec": "woff2",
    "nssutil3": "nss",
    "smime3": "nss",
    "dbus-glib-1": "dbus-glib",
    "dbusmenu-glib": "libdbusmenu-glib",
    "dbusmenu-gtk": "libdbusmenu-gtk",
    "gstvideo-1.0": "gst-plugins-base",
    "gstbase-1.0": "gst-plugins-base",
    "gstaudio-1.0": "gst-plugins-base",
    "gsttag-1.0": "gst-plugins-base",
}


class DependencyResolver:
    def __init__(self, cache_path=None):
        pass

    def resolve_sync(self, lib_name: str) -> ResolvedDependency:
        lib_base = lib_name.split(".so")[0]
        if lib_base.startswith("lib"):
            lib_base = lib_base[3:]

        if lib_base in DEP_MAP:
            return ResolvedDependency(
                original=lib_name, nixpkg=DEP_MAP[lib_base],
                confidence=1.0, source="dict",
            )

        close = difflib.get_close_matches(lib_base, DEP_MAP.keys(), n=1, cutoff=0.8)
        if close:
            return ResolvedDependency(
                original=lib_name, nixpkg=DEP_MAP[close[0]],
                confidence=0.8, source="fuzzy",
            )

        return ResolvedDependency(
            original=lib_name, nixpkg=None,
            confidence=0.0, source="unknown",
        )

    def resolve_all(self, libs: list[str]) -> tuple[list[str], list[str]]:
        resolved, unresolved = [], []
        seen = set()
        for lib in libs:
            r = self.resolve_sync(lib)
            if r.nixpkg:
                if r.nixpkg not in seen:
                    seen.add(r.nixpkg)
                    resolved.append(r.nixpkg)
            else:
                unresolved.append(lib)
        return resolved, unresolved
