{ pkgs ? import <nixpkgs> {} }:

let
  # Auto-generated by app2nix
  # Edit this file to customize the package

in

pkgs.stdenv.mkDerivation {
  pname = "__NAME__";
  version = "__VERSION__";
  src = ./.;

  nativeBuildInputs = [
    pkgs.autoPatchelfHook
__DEPS__
  ];

  buildInputs = [
__BUILD_DEPS__
  ];

  installPhase = ''
    runHook preInstall

    mkdir -p $out/bin
    mkdir -p $out/lib
    mkdir -p $out/share

    # Copy application files
    cp -r usr/share/* $out/share/ 2>/dev/null || true
    cp -r opt/* $out/opt/ 2>/dev/null || true

    # Create bin entry
__BIN_SETUP__

    runHook postInstall
  '';

  fixupOutput = "hook";
}