[package]
name = "app2nix-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
tempfile.workspace = true
walkdir.workspace = true
chrono.workspace = true
uuid.workspace = true
regex.workspace = true
sha2.workspace = true
indicatif.workspace = true
dirs.workspace = true
xdg.workspace = true
toml.workspace = true
tera.workspace = true
