name: Mypy

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]

jobs:
  mypy-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install mypy
      - run: mypy src/app2nix --ignore-missing-imports
